export const Specialists = [
  {label: 'Cardiologist', value: 'Cardiologist'},
  {label: 'Dermatologist', value: 'Dermatologist'},
  {label: 'Endocrinologist', value: 'Endocrinologist'},
  {label: 'Gastroenterologist', value: 'Gastroenterologist'},
  {label: 'Hematologist', value: 'Hematologist'},
  {
    label: 'Infectious Disease Specialist',
    value: 'Infectious Disease Specialist',
  },
  {label: 'Neurologist', value: 'Neurologist'},
  {label: 'Gynecologist', value: 'Gynecologist'},
  {label: 'Oncologist', value: 'Oncologist'},
  {label: 'Ophthalmologist', value: 'Ophthalmologist'},
  {label: 'Otolaryngologist', value: 'Otolaryngologist'},
  {label: 'Pediatrician', value: 'Pediatrician'},
  {label: 'Psychiatrist', value: 'Psychiatrist'},
  {label: 'Pulmonologist', value: 'Pulmonologist'},
  {label: 'Radiologist', value: 'Radiologist'},
  {label: 'Rheumatologist', value: 'Rheumatologist'},
  {label: 'Urologist', value: 'Urologist'},
  {label: 'Allergist', value: 'Allergist'},
  {label: 'Anesthesiologist', value: 'Anesthesiologist'},
  {label: 'Dentist', value: 'Dentist'},
  {label: 'Dietitian', value: 'Dietitian'},
  {
    label: 'Emergency Medicine Specialist',
    value: 'Emergency Medicine Specialist',
  },
  {label: 'Family Medicine Specialist', value: 'Family Medicine Specialist'},
  {label: 'General Practitioner', value: 'General Practitioner'},
  {label: 'Internist', value: 'Internist'},
  {label: 'Nephrologist', value: 'Nephrologist'},
  {label: 'Obstetrician', value: 'Obstetrician'},
  {label: 'Orthopedist', value: 'Orthopedist'},
];
